version: '3.8'
services:
  rba_backend:
    build: .
    container_name: rba_backend
    ports:
      - "3000:5001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Passw0rd
      DB_NAME: auth_db
    networks:
      - nodejs
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    
    networks:
      - nodejs
  
networks:
  nodejs:
    driver: bridge

volumes:
  db-data:

